type Query {
	# Tables
	tables: [Table!]!
	availableTables(date: String!, guestCount: Int): [Table!]!
	availableTablesRaw(date: String!, guestCount: Int): [Table!]!

	# Reservations / Bookings
	reservation(id: ID): Reservation!
	reservations: [Reservation!]!

	# Dishes
	menu(category: String): [Dish!]!
	dish(id: ID!): Dish
	dishesByCategory(category: String): [Dish!]!

	# # Guest
	# guestOrders(id: Int!): Guest!

	# Order
	guestOrders(guestId: Int!): [Order!]!
}

type Mutation {
	# Reservations / Bookings
	createReservation(input: CreateReservationInput!): Reservation!
	cancelReservation(id: ID!): Reservation!

	#Order
	createOrder(input: CreateOrderInput!): Order!
}

type Table {
	id: ID!
	tableNumber: String!
	capacity: Int!
	status: TableStatus!
	reservations: [Reservation!]!
}

type Reservation {
	id: Int!
	table: Table!
	customerName: String!
	customerPhone: String!
	reservationDate: String!
	guestCount: Int!
	status: ReservationStatus!
	guests: [Guest!]!
	totalAmount: Float!
}

type Guest {
	id: ID!
	reservation: Reservation!
	guestNumber: Int!
	orders: [Order!]!
	subtotal: Float!
}

type Dish {
	id: ID!
	name: String!
	description: String
	price: Float!
	category: String
	available: Boolean!
	orders: [Order!]!
}

type Order {
	id: ID!
	dish: Dish!
	guest: Guest!
	quantity: Int!
	subtotal: Float!
}

input CreateReservationInput {
	tableId: ID!
	customerName: String!
	customerPhone: String!
	reservationDate: String!
	guestCount: Int!
}

input CreateOrderInput {
	guestId: ID!
	dishId: ID!
	quantity: Int!
}

enum TableStatus {
	AVAILABLE
	RESERVED
	OCCUPIED
	BLOCKED
}

enum ReservationStatus {
	PENDING
	CONFIRMED
	CANCELLED
	COMPLETED
}
